export const EMPLOYEE_INFO_REQUEST = 'EMPLOYEE_INFO_REQUEST'
export const EMPLOYEE_INFO_SUCCESS = 'EMPLOYEE_INFO_SUCCESS'
export const EMPLOYEE_INFO_FAIL    = 'EMPLOYEE_INFO_FAIL'

export const EMPLOYEE_DASHBOARD_REQUEST = 'EMPLOYEE_DASHBOARD_REQUEST'
export const EMPLOYEE_DASHBOARD_SUCCESS = 'EMPLOYEE_DASHBOARD_SUCCESS'
export const EMPLOYEE_DASHBOARD_FAIL    = 'EMPLOYEE_DASHBOARD_FAIL'

export const EMPLOYEE_ACTIVE_REQUEST = 'EMPLOYEE_ACTIVE_REQUEST'
export const EMPLOYEE_ACTIVE_SUCCESS = 'EMPLOYEE_ACTIVE_SUCCESS'
export const EMPLOYEE_ACTIVE_FAIL    = 'EMPLOYEE_ACTIVE_FAIL'