export const EMPLOYEE_PROFILE_REQUEST = 'EMPLOYEE_PROFILE_REQUEST'
export const EMPLOYEE_PROFILE_SUCCESS = 'EMPLOYEE_PROFILE_SUCCESS'
export const EMPLOYEE_PROFILE_FAIL    = 'EMPLOYEE_PROFILE_FAIL'

export const EMPLOYEE_INFO_REQUEST = 'EMPLOYEE_INFO_REQUEST'
export const EMPLOYEE_INFO_SUCCESS = 'EMPLOYEE_INFO_SUCCESS'
export const EMPLOYEE_INFO_FAIL    = 'EMPLOYEE_INFO_FAIL'
